# last_updated: 2020-08-22
# authors: Jaekwon Lee
# title: Visualizing schedule results
# parameters:
#   - 1: WORK_PATH: base path for experiments
#   - 2: OUTPUT_PATH: output file from WORK_PATH
#   - 3: INTERMEDIATE_PATH: intermediate data file path from WORK_PATH that generated by python script
#   - 4: PRIORITY_PATH: priority file path from WORK_PATH
#   - 5: timeline per graph: the length of timeline per graph(default: 200ms)

options(warn=-1)
############################################################
# Load libraries
############################################################
getENV<-function(codeBase=NULL){
    # collect working environment information
    # - codeBase: only works when it is executed by IDE
    env<-list()
    args <- commandArgs(trailingOnly = FALSE)
    env$BASE <- getwd()
    fname <- args[startsWith(args,"--file=" )==TRUE]
    if (length(fname)!=0){
        fname <- substring(fname, 8)
        if (!startsWith(fname, "/") && !startsWith(fname, "~")){
            fname <- sprintf("%s/%s", env$BASE, fname)
        }
        env$FILE <- basename(fname)
        env$CODE_BASE <- dirname(fname)
        env$PARAMS <- commandArgs(trailingOnly = TRUE)
    }else{
        env$FILE <- ""
        env$CODE_BASE <- sprintf("%s/%s",getwd(), codeBase)
        env$PARAMS <- c()
    }
    return (env)
}
ENV<-getENV("scripts/schedule")   # the codeBase parameter is for debug, it will be ignored when this script is executed by RScript
ENV$PARAMS<- c("results/Test/ICS2", "draws/timeline_1_0.pdf", "draws/intermediate_1_0.csv", "_phase1/debug/sol1_sample0_priorities.json", 200)
print(sprintf("WORK_PATH : %s", ENV$BASE))
print(sprintf("FILE      : %s", ENV$FILE))
print(sprintf("CODE_BASE : %s", ENV$CODE_BASE))
print(sprintf("PARAMS    : %s", ENV$PARAMS))

setwd(ENV$CODE_BASE)
suppressMessages(library(jsonlite))
source("lib_schedule.R")
setwd(ENV$BASE)


##########################################
# drawing timelines
##########################################
{
    # parameter Setting
    BASE_PATH           <- sprintf("%s/%s", ENV$BASE, ENV$PARAMS[1])
    outputFile          <- sprintf("%s/%s", BASE_PATH, ENV$PARAMS[2])
    intermediateFile    <- sprintf("%s/%s", BASE_PATH, ENV$PARAMS[3])
    priorityFile        <- sprintf("%s/%s", BASE_PATH, ENV$PARAMS[4])
    OneGraphLength      <- as.integer(ENV$PARAMS[5])
    
    # load additional settings
    settings            <- parsingParameters(sprintf("%s/settings.txt",BASE_PATH))
    TASK_INFO           <- load_taskInfo(sprintf("%s/input.csv",BASE_PATH), settings$TIME_QUANTA)
    UNIT                <- settings$TIME_QUANTA
    
    cat(sprintf("Priority file    : %s\n", priorityFile))
    cat(sprintf("Intermediate file: %s\n", intermediateFile))
    cat(sprintf("Output file      : %s\n", outputFile))
    cat(sprintf("One graph length : %d\n", OneGraphLength))
    cat(sprintf("Task UNIT        : %f\n", UNIT))
    cat(sprintf("Generating timeline graph ...\n"))
    
    # load data
    OneGraphLength      <- OneGraphLength * (1/settings$TIME_QUANTA)
    priorities <- fromJSON(priorityFile) + 1 # make priority level to start from 1
    data <- data <- read.csv(intermediateFile, header=TRUE)
    draw_timeline(outputFile, data, priorities,
                  TASK_INFO, UNIT,
                  Step=OneGraphLength, thickBar=0.1, addTaskNum = TRUE, MaxGraphs=50)
    cat("Done\n")
}
